[workspace]
authors = ["Adam N <aniemcz@clemson.edu>"]
channels = ["pytorch", "nvidia", "conda-forge"]
name = "pixiRenoTest"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
gcc = "10.*"
gxx = "10.*"
pytorch = "2.2.1.*"
torchvision = "0.17.1.*"
torchaudio = "2.2.1.*"
pytorch-cuda = "11.8.*"
sparsehash = ">=2.0.4,<3"
numpy = "1.*"

[pypi-dependencies]
torchac = ">=0.9.3, <0.10"
open3d = ">=0.18.0, <0.19"
ninja = ">=1.11.1.4, <2"
rootpath = ">=0.1.1, <0.2"
wandb = ">=0.20.1, <0.21"
pyarrow = ">=20.0.0, <21"
fastparquet = ">=2024.11.0, <2025"
